import type { RawLinkedInPost } from "../types";

/** Curated demo posts for Best Pharma Co. — fictional content for sales demos. */
const BEST_PHARMA_SEED: RawLinkedInPost[] = [
  {
    id: "bpc-li-1",
    headline: "Q1 2026 Results: Strong Oncology Momentum",
    text: "Best Pharma Co. reports Q1 2026 revenue of $14.2B, up 8% year over year, driven by oncology and vaccine franchises. Full investor release on our newsroom.",
    postType: "Document",
    publishedAt: new Date(Date.now() - 52 * 86400000).toISOString(),
    reactions: 412,
    comments: 18,
    reposts: 67,
  },
  {
    id: "bpc-li-2",
    headline: "FDA Priority Review for BPC-401",
    text: "Our investigational PD-L1 inhibitor BPC-401 has received FDA Priority Review for first-line treatment of advanced non-small cell lung cancer. PDUFA date: September 2026.",
    postType: "Document",
    publishedAt: new Date(Date.now() - 45 * 86400000).toISOString(),
    reactions: 891,
    comments: 34,
    reposts: 142,
  },
  {
    id: "bpc-li-3",
    headline: "ASCO 2026: 42 Abstracts Accepted",
    text: "Team Best Pharma is heading to ASCO with 42 accepted abstracts across lung, breast, and hematologic malignancies — including four oral presentations.",
    postType: "Image",
    publishedAt: new Date(Date.now() - 38 * 86400000).toISOString(),
    reactions: 356,
    comments: 12,
    reposts: 58,
  },
  {
    id: "bpc-li-4",
    headline: "Patient Access Program Expansion",
    text: "We're expanding the Best Care Access program to 14 new markets, helping eligible patients start therapy without delay while coverage is confirmed.",
    postType: "Video",
    publishedAt: new Date(Date.now() - 31 * 86400000).toISOString(),
    reactions: 278,
    comments: 9,
    reposts: 41,
  },
  {
    id: "bpc-li-5",
    headline: "World Immunization Week",
    text: "Vaccines protect communities. This week we highlight our R&D teams advancing next-generation pneumococcal and RSV candidates — science built for public health.",
    postType: "Repost",
    publishedAt: new Date(Date.now() - 28 * 86400000).toISOString(),
    reactions: 198,
    comments: 6,
    reposts: 22,
  },
  {
    id: "bpc-li-6",
    headline: "2025 ESG & Sustainability Report",
    text: "Patients first, planet forward: our 2025 report covers carbon reduction targets, clinical trial diversity metrics, and community health partnerships.",
    postType: "Document",
    publishedAt: new Date(Date.now() - 24 * 86400000).toISOString(),
    reactions: 167,
    comments: 4,
    reposts: 19,
  },
  {
    id: "bpc-li-7",
    headline: "Rare Disease Awareness Poll",
    text: "Poll: What percentage of rare diseases have an FDA-approved treatment? (Answer: fewer than 10% — underscoring why we invest in orphan drug R&D.)",
    postType: "Poll",
    publishedAt: new Date(Date.now() - 21 * 86400000).toISOString(),
    reactions: 124,
    comments: 22,
    reposts: 8,
  },
  {
    id: "bpc-li-8",
    headline: "Maria's Story — Living with RA",
    text: "When Maria was diagnosed with rheumatoid arthritis, she needed clarity and a care team that listened. Her story reflects why we design support around real patient journeys.",
    postType: "Video",
    publishedAt: new Date(Date.now() - 17 * 86400000).toISOString(),
    reactions: 445,
    comments: 31,
    reposts: 52,
  },
  {
    id: "bpc-li-9",
    headline: "Best Pharma Patient Advisory Council",
    text: "Patients and caregivers shape our trials, labels, and access programs. Meet the 2026 Patient Advisory Council — lived experience at the center of every decision.",
    postType: "Video",
    publishedAt: new Date(Date.now() - 14 * 86400000).toISOString(),
    reactions: 312,
    comments: 14,
    reposts: 36,
  },
  {
    id: "bpc-li-10",
    headline: "Voices of Leadership: Dr. James Okonkwo, R&D",
    text: "Dr. Okonkwo leads our translational oncology group. He shares how cross-functional teams move from bench to bedside — and what 'urgency with rigor' means at Best Pharma.",
    postType: "Document",
    publishedAt: new Date(Date.now() - 10 * 86400000).toISOString(),
    reactions: 289,
    comments: 11,
    reposts: 28,
  },
  {
    id: "bpc-li-11",
    headline: "Health Policy Forum: Step Therapy",
    text: "Step therapy can delay access to the therapy a clinician already selected. We're working with patient groups on policy solutions that put clinical judgment first.",
    postType: "Repost",
    publishedAt: new Date(Date.now() - 7 * 86400000).toISOString(),
    reactions: 156,
    comments: 8,
    reposts: 15,
  },
  {
    id: "bpc-li-12",
    headline: "Great Place to Work Certification",
    text: "Best Pharma Co. earned Great Place to Work certification across our U.S. and EU hubs — culture that attracts the scientists and communicators advancing global health.",
    postType: "Image",
    publishedAt: new Date(Date.now() - 4 * 86400000).toISOString(),
    reactions: 534,
    comments: 19,
    reposts: 44,
  },
];

export async function fetchPostsFromSeed(): Promise<RawLinkedInPost[]> {
  return BEST_PHARMA_SEED;
}
